# Generated by Django 6.0.3 on 2026-04-13 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artists/')),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artist'),
            preserve_default=False,
        ),
    ]
